image: openjdk:25-ea-jdk

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - check
  - test
  - build
  - security
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

variables:
  CI_IMAGE_BASE: $CI_REGISTRY/$CI_PROJECT_PATH/orch-api
  CI_IMAGE_STAGING: $CI_IMAGE_BASE:staging
  CI_IMAGE_PROD: $CI_IMAGE_BASE:prod
  CI_IMAGE_LATEST: $CI_IMAGE_BASE:latest

  GHCR_IMAGE_BASE: $GITHUB_REGISTRY/$GITHUB_OWNER/$CI_PROJECT_NAME
  GHCR_IMAGE: $GHCR_IMAGE_BASE/orch-api

  SAST_JAVA_VERSION: "25"
  GITLAB_ADVANCED_SAST_ENABLED: "true"
  GIT_DEPTH: "0"
  DOCKER_TLS_CERTDIR: ""
  CS_IMAGE: $CI_IMAGE_LATEST

.docker_login: &docker_login
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.docker_login_ghcr: &docker_login_ghcr
  - docker info
  - echo "$GITHUB_TOKEN" | docker login $GITHUB_REGISTRY -u $GITHUB_USERNAME --password-stdin

.docker_buildx: &docker_buildx
  - docker context create fedDB-context || true
  - docker buildx create --name fedDBBuilder --use fedDB-context || docker buildx use fedDBBuilder
  - docker buildx inspect --bootstrap

.docker_buildxrm: &docker_buildxrm
  - docker buildx rm fedDBBuilder || true


#https://docs.gitlab.com/ci/jobs/job_rules/#reuse-rules-in-different-jobs
.security_default_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: manual

check:build:
  stage: check
  script:
    - ./mvnw install -DskipTests
  artifacts:
    paths:
      - target
  rules:
    - when: always

.check:build:docker:
  image: docker:24.0.2
  stage: check
  dependencies:
    - check:build
  needs:
    - check:build
  services:
    - name: docker:24.0.2-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - *docker_login
  script:
    - docker build -t $CI_IMAGE -f src/main/docker/Dockerfile.jvm .
    - docker save -o image-latest.tar $CI_IMAGE
    - chmod 644 image-latest.tar
    - echo "API image created at image-latest.tar"
  artifacts:
    paths:
      - image-latest.tar
    expire_in: 1 hour

check:build:docker:staging:
  extends: .check:build:docker
  variables:
    CI_IMAGE: $CI_IMAGE_STAGING
  rules:
    - when: always

# ─────────────────────────────────────────────────────────────────────────────
# test

test:linters:
  stage: test
  image: openjdk:25-ea-jdk
  script:
    - ./mvnw clean verify -DskipTests
  artifacts:
    when: always
    paths:
      - target/*.xml
      - target/gl-code-quality-report.json
    reports:
      codequality:
        - target/gl-code-quality-report.json
  allow_failure: true

# ─────────────────────────────────────────────────────────────────────────────
# deploy

.deploy:gitlab_registry:
  image: docker:24.0.2
  stage: deploy
  services:
    - name: docker:24.0.2-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - *docker_login
    - *docker_buildx
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 --provenance false -t $CI_IMAGE -f ./$DOCKERFILE --push .

.deploy:github_registry:
  image: docker:24.0.2
  stage: deploy
  services:
    - name: docker:24.0.2-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - *docker_login_ghcr
    - *docker_buildx
  script:
    - docker buildx build --platform linux/amd64,linux/arm64/v8 --provenance false -t $CI_IMAGE -f ./$DOCKERFILE --push .


deploy:gitlab_registry:staging:
  extends: .deploy:gitlab_registry
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  variables:
    CI_IMAGE: $CI_IMAGE_STAGING
    DOCKERFILE: src/main/docker/Dockerfile.jvm

deploy:gitlab_registry:latest:
  extends: .deploy:gitlab_registry
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    CI_IMAGE: $CI_IMAGE_LATEST
    DOCKERFILE: src/main/docker/Dockerfile.jvm

deploy:github_registry:develop:
  extends: .deploy:github_registry
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  dependencies:
    - check:build
  needs:
    - check:build
  variables:
    CI_IMAGE: $GHCR_IMAGE
    DOCKERFILE: src/main/docker/Dockerfile.jvm

deploy:github_registry:main:
  extends: .deploy:github_registry
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"
  dependencies:
    - check:build
  needs:
    - check:build
  variables:
    CI_IMAGE: $GHCR_IMAGE
    DOCKERFILE: src/main/docker/Dockerfile.jvm

# ─────────────────────────────────────────────────────────────────────────────
# Override all security scanning jobs

spotbugs-sast:
  dependencies:
    - check:build
  rules:
    - !reference [ .security_default_rules, rules ]
  variables:
    COMPILE: "false"
    SECURE_LOG_LEVEL: debug

gitlab-advanced-sast:
  dependencies:
    - check:build
  rules:
    - !reference [ .security_default_rules, rules ]
  artifacts:
    paths:
      - '**/trace.ctf'
    expire_in: 1 week
    when: always
  variables:
    RUNNER_SCRIPT_TIMEOUT: 50m
  timeout: 1h

container_scanning:
  stage: security
  needs:
    - check:build:docker:staging
  dependencies:
    - check:build:docker:staging
  rules:
    - !reference [ .security_default_rules, rules ]
  variables:
    CS_IMAGE: "archive://image-latest.tar"

secret_detection:
  dependencies:
    - check:build
  stage: security
  rules:
    - !reference [ .security_default_rules, rules ]
  variables:
    GIT_DEPTH: 100

gemnasium-maven-dependency_scanning:
  rules:
    - !reference [ .security_default_rules, rules ]