
    create table container_logs (
        id bigint generated by default as identity,
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        log TEXT not null,
        container_run_id bigint,
        primary key (id)
    );

    create table container_runs (
        id bigint generated by default as identity,
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        app_id bigint not null,
        app_image varchar(255) not null,
        container_id varchar(255),
        container_name varchar(255) not null,
        status varchar(255) check ((status in ('INIT','RUNNING','STARTED','STOPPED','FAILED','COMPLETED','ABORTED','UNKNOWN'))),
        workflow_id bigint not null,
        primary key (id)
    );

    alter table if exists container_logs 
       add constraint FK7vyp7tg4gks28cmd97163f85t 
       foreign key (container_run_id) 
       references container_runs;
